# Data Toolbox 2 Case Study #

Daha önce öğrenen tüm tüm fonksiyonların kullanılacağı bir inceleme yapacağız. Bunlar için Dünya Bankasının yayınladığı dataları kullanacağız.

***zip()*** foksiyonu

In [1]:
numbers=[1,2,3]
letters=["a","b","c"]

In [2]:
type(numbers)

list

In [3]:
type(letters)

list

In [5]:
zipped=zip(numbers,letters)

In [6]:
type(zipped)

zip

In [7]:
print(zipped) # Direkt olarak değerleri alamıyoruz. Bunun için ya bir iterasyona sokmak yada liste haline getirmek lazım.

<zip object at 0x000001459D258348>

In [8]:
zip_list=list(zipped)

In [9]:
print(zip_list)

[(1, 'a'), (2, 'b'), (3, 'c')]

In [13]:
# Burada iki tane set objesi tanımladık. Zip ile iki set  birleştirildiğinde normalde sıralı olarak veriler verilmesed zip
# operasyonu ile birleştirildiğinde sıralı hale gelir.
s1={2,3,1}
s2={"b","a","c"}

In [20]:
type(s1)
s1

{1, 2, 3}

In [21]:
type(s2)
s2

{'a', 'b', 'c'}

In [17]:
zip_set=zip(s1,s2)

In [18]:
print(list(zip_set)) # Çıktı sıralı bir şekilde olacaktır.

[(1, 'a'), (2, 'b'), (3, 'c')]

In [22]:
# Değişik uzunlukta iterable verilirse en kısa olanının element sayısı kadar zip objesi yaratır. Gerisini ignore eder.
list(zip(range(5),range(100)))

[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]

In [28]:
# Eğer en uzun olana göre zip objesini oluşturup diğerlerini boş bırakmak istiyor isek. 
# zip yerine itertools.zip_longest() kullanabiliriz.
from itertools import zip_longest

numbers = [1, 2, 3]
letters = ['a', 'b', 'c']
longest = range(5)
zipped=zip_longest(numbers,letters,longest,fillvalue="?")
list(zipped)

[(1, 'a', 0), (2, 'b', 1), (3, 'c', 2), ('?', '?', 3), ('?', '?', 4)]

In [29]:
import pandas as pd

In [36]:
df_country=pd.read_csv("C:\WorldBankData\WDICountry.csv")

In [37]:
df_country

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,...,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Unnamed: 30
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,NaN,Latin America & Caribbean,High income,AW,...,NaN,Enhanced General Data Dissemination System (e-...,2010,NaN,NaN,Yes,NaN,NaN,2016.0,NaN
1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,NaN,South Asia,Low income,AF,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2017.0,NaN
2,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,NaN,Sub-Saharan Africa,Lower middle income,AO,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2014,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2017.0,NaN
3,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,2011,"Demographic and Health Survey, 2017/18",Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2017.0,NaN
4,AND,Andorra,Andorra,Principality of Andorra,AD,Euro,NaN,Europe & Central Asia,High income,AD,...,NaN,NaN,2011. Population data compiled from administra...,NaN,NaN,Yes,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
258,XKX,Kosovo,Kosovo,Republic of Kosovo,XK,Euro,NaN,Europe & Central Asia,Upper middle income,XK,...,NaN,Enhanced General Data Dissemination System (e-...,2011,"Multiple Indicator Cluster Survey, 2013/14","Expenditure survey/budget survey (ES/BS), 2015",NaN,2014,NaN,NaN,NaN
259,YEM,Yemen,"Yemen, Rep.",Republic of Yemen,YE,Yemeni rial,NaN,Middle East & North Africa,Low income,RY,...,NaN,Enhanced General Data Dissemination System (e-...,2004,"Demographic and Health Survey, 2013","Expenditure survey/budget survey (ES/BS), 2014",NaN,NaN,2012.0,2017.0,NaN
260,ZAF,South Africa,South Africa,Republic of South Africa,ZA,South African rand,Fiscal year end: March 31; reporting period fo...,Sub-Saharan Africa,Upper middle income,ZA,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey, 2016","Expenditure survey/budget survey (ES/BS), 2014/15",NaN,2007,2010.0,2017.0,NaN
261,ZMB,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,National accounts data were rebased to reflect...,Sub-Saharan Africa,Lower middle income,ZM,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2010,"Demographic and Health Survey, 2013/14","Integrated household survey (IHS), 2015",NaN,NaN,1994.0,2017.0,NaN
262,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,NaN,Sub-Saharan Africa,Lower middle income,ZW,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2012,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2011/12",NaN,NaN,NaN,2017.0,NaN

In [54]:
file_data=pd.read_csv("C:\WorldBankData\WDIData.csv", chunksize=1000) # Büyük datayı chunksize ile her seferinde tek parça yükle

In [55]:
df_data=pd.DataFrame(next(file_data)) # içindeki veriyi getirebilmek için next() ile çağırılmalıdır.

In [56]:
df_data_ARB=df_data[df_data["Country Code"]=="ARB"]

In [57]:
df_data_ARB

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Unnamed: 64
0,Arab World,ARB,"2005 PPP conversion factor, GDP (LCU per inter...",PA.NUS.PPP.05,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,"2005 PPP conversion factor, private consumptio...",PA.NUS.PRVT.PP.05,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World,ARB,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.278329e+01,8.312030e+01,8.353346e+01,8.389760e+01,8.417160e+01,8.451017e+01,NaN,NaN,NaN,NaN
3,Arab World,ARB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,8.642827e+01,8.707058e+01,8.817684e+01,8.734274e+01,8.913012e+01,8.967869e+01,9.027369e+01,NaN,NaN,NaN
4,Arab World,ARB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.394210e+01,7.524410e+01,7.716230e+01,7.553898e+01,7.874115e+01,7.966564e+01,8.074929e+01,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Arab World,ARB,"Population ages 0-14, female (% of female popu...",SP.POP.0014.FE.ZS,4.265679e+01,4.301615e+01,4.334689e+01,4.363157e+01,4.383702e+01,4.394996e+01,...,3.398967e+01,3.380500e+01,3.365844e+01,3.352812e+01,3.339686e+01,3.339139e+01,3.332863e+01,3.323247e+01,NaN,NaN
996,Arab World,ARB,"Population ages 0-14, male",SP.POP.0014.MA.IN,2.039930e+07,2.113528e+07,2.187122e+07,2.260432e+07,2.332883e+07,2.404180e+07,...,6.231513e+07,6.337934e+07,6.451472e+07,6.567016e+07,6.680020e+07,6.811218e+07,6.928004e+07,7.037917e+07,NaN,NaN
997,Arab World,ARB,"Population ages 0-14, male (% of male population)",SP.POP.0014.MA.ZS,4.388672e+01,4.425740e+01,4.457219e+01,4.482577e+01,4.500656e+01,4.511092e+01,...,3.318643e+01,3.299040e+01,3.284803e+01,3.272687e+01,3.260065e+01,3.257064e+01,3.247996e+01,3.235941e+01,NaN,NaN
998,Arab World,ARB,"Population ages 0-14, total",SP.POP.0014.TO,3.990028e+07,4.133970e+07,4.279288e+07,4.424895e+07,4.568528e+07,4.708985e+07,...,1.219345e+08,1.240076e+08,1.262137e+08,1.284498e+08,1.306295e+08,1.331906e+08,1.354687e+08,1.376092e+08,NaN,NaN
999,Arab World,ARB,"Population ages 05-09, female (% of female pop...",SP.POP.0509.FE.5Y,1.401427e+01,1.422199e+01,1.434377e+01,1.436545e+01,1.431357e+01,1.422870e+01,...,1.104770e+01,1.098729e+01,1.096119e+01,1.096149e+01,1.097374e+01,1.102306e+01,1.110618e+01,1.120801e+01,NaN,NaN